/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Logica_Operaciones_BD.OperarcionesCRUD;
import java.lang.reflect.Array;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author edand
 */
public class Cliente extends javax.swing.JInternalFrame {

    String usuario;

    public static Date fechaactual = new Date();
    public static SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy");

    public static String cod;

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        usuario = Login.user;
        Titulo.setText("Clientes>>Cliente");
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        JDesktopCliente.setVisible(false);      
        JBNombres.setVisible(false);
        JBApellidos.setVisible(false);
        JBCorreo.setVisible(false);
        JBEdad.setVisible(false);
        JBDireccion.setVisible(false);
        JBDireccion1.setVisible(false);
    }

    private boolean cerrado(Object obj) {
        JInternalFrame[] FrmActivo = JDesktopCliente.getAllFrames();
        boolean cerrado = true;
        int i = 0;
        while (i < FrmActivo.length && cerrado) {
            if (FrmActivo[i] == obj) {
                cerrado = false;
            }
            i++;
        }
        return cerrado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        JBSalir = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jToolBar2 = new javax.swing.JToolBar();
        JBConsultar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        JDesktopCliente = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LabelCedula = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LabelIngreso = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jToolBar3 = new javax.swing.JToolBar();
        JBGuardar = new javax.swing.JButton();
        JBActualizar = new javax.swing.JButton();
        JBSalir1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LabelFechActualizacion = new javax.swing.JLabel();
        JBNombres = new javax.swing.JButton();
        JBApellidos = new javax.swing.JButton();
        JBCorreo = new javax.swing.JButton();
        JBEdad = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        idUser = new javax.swing.JLabel();
        JBDireccion = new javax.swing.JButton();
        JBDireccion1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clasificacion.png"))); // NOI18N

        jToolBar1.setRollover(true);
        jToolBar1.setBorderPainted(false);
        jToolBar1.setEnabled(false);

        JBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salida.png"))); // NOI18N
        JBSalir.setToolTipText("Salir");
        JBSalir.setFocusable(false);
        JBSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(JBSalir);
        jToolBar1.add(Titulo);

        jLabel1.setText("Cedula:");

        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        jToolBar2.setRollover(true);
        jToolBar2.setBorderPainted(false);
        jToolBar2.setEnabled(false);

        JBConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/consulta.png"))); // NOI18N
        JBConsultar.setToolTipText("Consultar");
        JBConsultar.setFocusable(false);
        JBConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBConsultarActionPerformed(evt);
            }
        });
        jToolBar2.add(JBConsultar);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actualizar.png"))); // NOI18N
        jButton1.setToolTipText("LimpiarDatos");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton1);

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jLabel2.setText("Cedula:");

        jLabel3.setText("Usuario:");

        jLabel4.setText("Fecha de Ingreso:");

        jLabel5.setText("Nombres:");

        jLabel6.setText("Apellidos:");

        jToolBar3.setRollover(true);
        jToolBar3.setBorderPainted(false);
        jToolBar3.setEnabled(false);

        JBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disco-flexible.png"))); // NOI18N
        JBGuardar.setToolTipText("Guardar");
        JBGuardar.setFocusable(false);
        JBGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGuardarActionPerformed(evt);
            }
        });
        jToolBar3.add(JBGuardar);

        JBActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lapiz.png"))); // NOI18N
        JBActualizar.setToolTipText("ActualizarDatos");
        JBActualizar.setFocusable(false);
        JBActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBActualizarActionPerformed(evt);
            }
        });
        jToolBar3.add(JBActualizar);

        JBSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salida.png"))); // NOI18N
        JBSalir1.setToolTipText("Salir");
        JBSalir1.setFocusable(false);
        JBSalir1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBSalir1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JBSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalir1ActionPerformed(evt);
            }
        });
        jToolBar3.add(JBSalir1);

        jLabel7.setText("Correo:");

        jLabel8.setText("Edad:");

        jLabel9.setText("Fecha de Actualizacion:");

        JBNombres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/acerca-de.png"))); // NOI18N
        JBNombres.setToolTipText("Ingrese los Nombres");
        JBNombres.setBorder(null);

        JBApellidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/acerca-de.png"))); // NOI18N
        JBApellidos.setToolTipText("Ingrese los Apellidos");
        JBApellidos.setBorder(null);

        JBCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/acerca-de.png"))); // NOI18N
        JBCorreo.setToolTipText("Ingrese el Correo");
        JBCorreo.setBorder(null);

        JBEdad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/acerca-de.png"))); // NOI18N
        JBEdad.setToolTipText("Ingrese la Edad");
        JBEdad.setBorder(null);

        jLabel11.setText("Cliente:");

        jLabel12.setText("Direccion:");

        jLabel13.setText("Comentario");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        JBDireccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/acerca-de.png"))); // NOI18N
        JBDireccion.setToolTipText("Ingrese la dirección");
        JBDireccion.setBorder(null);

        JBDireccion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/acerca-de.png"))); // NOI18N
        JBDireccion1.setToolTipText("Ingrese comentario");
        JBDireccion1.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtdireccion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(txtNombres, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JBApellidos, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(JBNombres, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JBDireccion))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBDireccion1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(LabelCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(JBEdad))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163)
                                .addComponent(jLabel9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(187, 187, 187))
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addComponent(JBCorreo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(idUser, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LabelIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(LabelFechActualizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(labelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(90, Short.MAX_VALUE))
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(LabelIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                    .addComponent(LabelCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(idUser, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(LabelFechActualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(LabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JBCorreo))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(labelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)))
                    .addComponent(JBNombres))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JBEdad))
                    .addComponent(JBApellidos))
                .addGap(34, 34, 34)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBDireccion))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBDireccion1))
                .addGap(324, 324, 324))
        );

        JDesktopCliente.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JDesktopClienteLayout = new javax.swing.GroupLayout(JDesktopCliente);
        JDesktopCliente.setLayout(JDesktopClienteLayout);
        JDesktopClienteLayout.setHorizontalGroup(
            JDesktopClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JDesktopClienteLayout.setVerticalGroup(
            JDesktopClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JDesktopCliente)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JDesktopCliente))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_JBSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtCedula.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed
//Consultar los datos del cliente en la base de datos
    private void JBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBConsultarActionPerformed
        String cedula = txtCedula.getText();
        LabelCedula.setText(cedula);

        if (!cedula.equals("")) {
            try {
                OperarcionesCRUD op = OperarcionesCRUD.getInstance();
              //  ArrayList<Vector<String>> ma = op.cedulaUsuario(usuario);
                
                
                ArrayList<Vector<String>> matriz = op.cedulaCliente(cedula);                
                Panel1.setVisible(false);
                JDesktopCliente.setVisible(true);
                

                for (Vector<String> vector : matriz) {
                    String idclient, cedul, nombres, apellidos, email, direccion, edad, username, idusuario, fechaIngr, fechaAct, comentario;

                    idclient = vector.get(0);
                    cedul = vector.get(1);
                    nombres = vector.get(2);
                    apellidos = vector.get(3);
                    email = vector.get(4);
                    direccion = vector.get(5);
                    edad = vector.get(6);
                    username = vector.get(7);
                    idusuario = vector.get(8);
                    fechaIngr = vector.get(9);
                    fechaAct = vector.get(10);
                    comentario = vector.get(11);

                    labelCliente.setText(idclient);
                    LabelCedula.setText(cedul);
                    txtNombres.setText(nombres);
                    txtApellidos.setText(apellidos);
                    txtCorreo.setText(email);
                    txtdireccion.setText(direccion);
                    txtEdad.setText(edad);
                    LabelUsuario.setText(username);
                    idUser.setText(idusuario);
                    LabelIngreso.setText(fechaIngr);
                    LabelFechActualizacion.setText(fechaAct);

                }

            } catch (SQLException err) {
                err.printStackTrace();

            }

        } else {
            JOptionPane.showMessageDialog(null, "Ingrese la Cedula por favor");
        }
    }//GEN-LAST:event_JBConsultarActionPerformed

    private void JBSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalir1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_JBSalir1ActionPerformed
//Actualizar datos del Cliente
    private void JBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBActualizarActionPerformed

        ArrayList<Vector<String>> matriz = new ArrayList<>();

        String fechas = fecha.format(fechaactual);
        String nombres, apellidos, edad, correo, usuarios, fechaact, cedula;
        int validacion = 0;
        cedula = LabelCedula.getText().trim();
        nombres = txtNombres.getText();
        apellidos = txtApellidos.getText();
        edad = txtEdad.getText();
        correo = txtCorreo.getText();
        fechaact = fechas;
        usuarios = usuario;

        if (nombres.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese los nombres por favor");
            JBNombres.setVisible(true);
            validacion++;
        }
        if (apellidos.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese los apellidos por favor");
            JBApellidos.setVisible(true);
            validacion++;
        }
        if (edad.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese la edad por favor");
            JBCorreo.setVisible(true);
            validacion++;
        }
        if (correo.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese el correo por favor");
            JBEdad.setVisible(true);
            validacion++;
        }
        if (validacion == 0) {
            
            Vector<String> datos = new Vector<>();
            datos.add(cedula);
            datos.add(nombres);
            datos.add(apellidos);
            datos.add(edad);
            datos.add(correo);
            datos.add(fechaact);
            datos.add(usuarios);

            matriz.add(datos);
        } else {
            JOptionPane.showMessageDialog(this, "Debe Ingresar todos los datos");
         
        }

        OperarcionesCRUD op = OperarcionesCRUD.getInstance();

        try {
            op.ActulizarDatoS(matriz);

        } catch (SQLException err) {
            err.printStackTrace();
        }


    }//GEN-LAST:event_JBActualizarActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void JBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGuardarActionPerformed
        ArrayList<Vector<String>> matriz = new ArrayList<>();

        Date fechaI = new Date();
        Date fechaA = new Date();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String fechaIngreso = formato.format(fechaI);
        String fechaActual = formato.format(fechaA);

        int validacion = 0;

        String  cedul, nombres, apellidos, email, direccion, edad, username, idusuario, comentario;

        cedul = LabelCedula.getText().toString();
        nombres = txtNombres.getText();
        apellidos = txtApellidos.getText();
        email = txtCorreo.getText();
        direccion = txtdireccion.getText();
        edad = txtEdad.getText();
        username = usuario;
        idusuario = idUser.getText().toString();
        comentario = jTextArea1.getText();

        if (nombres.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese los nombres por favor");
            JBNombres.setVisible(true);
            validacion++;
        }
        if (apellidos.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese los apellidos por favor");
            JBApellidos.setVisible(true);
            validacion++;
        }
        if (edad.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese la edad por favor");
            JBCorreo.setVisible(true);
            validacion++;
        }
        if (email.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese el correo por favor");
            JBEdad.setVisible(true);
            validacion++;
        }
        if (direccion.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese la direccion por favor");
            JBDireccion.setVisible(true);
            validacion++;
        }
        if (comentario.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese comentario por favor");
            JBDireccion1.setVisible(true);
            validacion++;
        }

        if (validacion == 0) {
            Vector<String> datos = new Vector<>();
            datos.add(cedul);
            datos.add(nombres);
            datos.add(apellidos);
            datos.add(email);
            datos.add(direccion);
            datos.add(edad);
            datos.add(usuario);
            datos.add(idusuario);
            datos.add(fechaIngreso);
            datos.add(fechaActual);
            datos.add(comentario);

            matriz.add(datos);
        } else {
            JOptionPane.showMessageDialog(this, "Debe Ingresar todos los datos");
        }

        try {
            OperarcionesCRUD op = OperarcionesCRUD.getInstance();
            op.InsertarPersona(matriz);
        } catch (SQLException err) {
            err.printStackTrace();
        }

    }//GEN-LAST:event_JBGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBActualizar;
    private javax.swing.JButton JBApellidos;
    private javax.swing.JButton JBConsultar;
    private javax.swing.JButton JBCorreo;
    private javax.swing.JButton JBDireccion;
    private javax.swing.JButton JBDireccion1;
    private javax.swing.JButton JBEdad;
    private javax.swing.JButton JBGuardar;
    private javax.swing.JButton JBNombres;
    private javax.swing.JButton JBSalir;
    private javax.swing.JButton JBSalir1;
    private javax.swing.JDesktopPane JDesktopCliente;
    private javax.swing.JLabel LabelCedula;
    private javax.swing.JLabel LabelFechActualizacion;
    private javax.swing.JLabel LabelIngreso;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JPanel Panel1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel idUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtdireccion;
    // End of variables declaration//GEN-END:variables
}
