/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Logica_Operaciones_BD.OperarcionesCRUD;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class ClienteCelular extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClienteCelular
     */
    String idCliente, numero, tipoCelular, empresa, descripcion;

    public ClienteCelular() {
        initComponents();
        labelTitulo.setText("Actualización Datos Celular del cliente : ");

    }

    public void setIdCliente(String id, String celula, String tipoCelula, String empres, String descripcio) {
        this.idCliente = id;
        this.numero = celula;
        this.tipoCelular = tipoCelula;
        this.empresa = empres;
        this.descripcion = descripcio;

        labelIDCLiente.setText(idCliente);

        DefaultTableModel modelo = (DefaultTableModel) tablaCelular.getModel();
        modelo.setRowCount(0);

        Vector<String> datos = new Vector<>();
        datos.add(numero);
        datos.add(tipoCelular);
        datos.add(empresa);
        datos.add(descripcion);

        modelo.addRow(datos);
    }

    public Vector<String> Celular() {
        Vector<String> datos = new Vector<>();
        //Muy buena observación, Edgar 👌. La razón por la que el método getValueAt(int row, int column) devuelve un Object es porque un JTable puede contener diferentes tipos de datos en sus columnas (Strings, enteros, booleanos, fechas, etc.).
        //Al devolver , el  es flexible y tú haces el cast al tipo correcto

        DefaultTableModel modelo = (DefaultTableModel) tablaCelular.getModel();
        datos.add(idCliente);
        //Si datos es una variable global, corres el riesgo de acumular valores cada vez que llames al método. Lo más seguro es inicializarlo dentro del método:
        int fila = 0;
        for (int col = 0; col < modelo.getColumnCount(); col++) {
            datos.add(String.valueOf(modelo.getValueAt(fila, col)));
        }

        return datos;

    }

    public void Guardar() {
        Vector<String> valores = Celular();
        try {
            OperarcionesCRUD op = OperarcionesCRUD.getInstance();
            op.ActualizarCelular(valores);
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        labelIDCLiente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCelular = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/llamada-telefonica.png"))); // NOI18N

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disco-flexible.png"))); // NOI18N
        jButton1.setToolTipText("Guardar");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salida.png"))); // NOI18N
        jButton2.setToolTipText("Salir");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(labelTitulo);
        jToolBar1.add(labelIDCLiente);

        tablaCelular.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Número", "Tipo", "Empresa", "Descripcion"
            }
        ));
        tablaCelular.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaCelular);
        if (tablaCelular.getColumnModel().getColumnCount() > 0) {
            tablaCelular.getColumnModel().getColumn(0).setResizable(false);
            tablaCelular.getColumnModel().getColumn(1).setResizable(false);
            tablaCelular.getColumnModel().getColumn(2).setResizable(false);
            tablaCelular.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Guardar();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelIDCLiente;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTable tablaCelular;
    // End of variables declaration//GEN-END:variables
}
