/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Logica_Operaciones_BD.OperarcionesCRUD;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class ComprasDiarias extends javax.swing.JInternalFrame {

    String usuario;

    /**
     * Creates new form AprobarCompra
     */
    public ComprasDiarias() {
        initComponents();
        labelTitulo.setText("Mercadería>ComprasDiarias");
        usuario = Login.user;
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        LocalDate fechaAc = LocalDate.now();

        String fecha;
        String estado = "Procesado";
        fecha = fechaAc.format(DateTimeFormatter.ISO_DATE);

        try {
            OperarcionesCRUD op = OperarcionesCRUD.getInstance();
            ArrayList<Vector<String>> matriz = op.InventarioFecha(fecha, estado);

            DefaultTableModel modelo = (DefaultTableModel) TablaAprobar.getModel();
            modelo.setRowCount(0);

            for (Vector<String> vector : matriz) {
                modelo.addRow(vector);

//                TablaAprobar.addMouseListener(new MouseAdapter() {
//                    @Override
//                    public void mouseClicked(MouseEvent e) {
//
//                        int fila_point = TablaAprobar.rowAtPoint(e.getPoint());
//                        int columna_point = 0;
//
//                        if (fila_point > -1) {
//                            
//                            String nombreProd, orden, nombreProveee, cantidad, totaCompra;
//
//                            nombreProd = vector.get(2);
//                            orden = vector.get(1);
//                            nombreProveee = vector.get(4);
//                            cantidad = vector.get(7);
//                            totaCompra = vector.get(8);
//
//                            txtNombreProducto.setText(nombreProd);
//                            txtOrden.setText(orden);
//                            txtNombreProveedor.setText(nombreProveee);
//                            txtCantidad.setText(cantidad);
//                            txtTotalCompra.setText(totaCompra);
//
//                        }
//
//                    }
//                });
            }
        } catch (SQLException err) {
            err.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaAprobar = new javax.swing.JTable();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aprobado.png"))); // NOI18N

        jToolBar1.setRollover(true);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actualizar-flecha.png"))); // NOI18N
        jButton4.setToolTipText("Actualizar Tabla");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salida.png"))); // NOI18N
        jButton1.setToolTipText("Salir");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(labelTitulo);

        TablaAprobar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codproductos", "Orden Compra", "Nombre Producto", "Usuario", "Proveedor", "Detalle", "Fecha_registro", "Cantidad", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaAprobar.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaAprobar);
        if (TablaAprobar.getColumnModel().getColumnCount() > 0) {
            TablaAprobar.getColumnModel().getColumn(0).setResizable(false);
            TablaAprobar.getColumnModel().getColumn(1).setResizable(false);
            TablaAprobar.getColumnModel().getColumn(2).setResizable(false);
            TablaAprobar.getColumnModel().getColumn(3).setResizable(false);
            TablaAprobar.getColumnModel().getColumn(4).setResizable(false);
            TablaAprobar.getColumnModel().getColumn(5).setResizable(false);
            TablaAprobar.getColumnModel().getColumn(6).setResizable(false);
            TablaAprobar.getColumnModel().getColumn(7).setResizable(false);
            TablaAprobar.getColumnModel().getColumn(8).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(203, 203, 203))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            LocalDate fechaA = LocalDate.now();
            String fecha = fechaA.format(DateTimeFormatter.ISO_DATE);
            String estado = "Procesado";

            OperarcionesCRUD op = OperarcionesCRUD.getInstance();
            ArrayList<Vector<String>> matriz = op.InventarioFecha(fecha, estado);

            DefaultTableModel modelo = (DefaultTableModel) TablaAprobar.getModel();
            modelo.setRowCount(0);

            for (Vector<String> vector : matriz) {
                modelo.addRow(vector);

            }

        } catch (SQLException err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaAprobar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
