/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import Logica_Operaciones_BD.OperarcionesCRUD;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class IngresoMercaderiaPorLote extends javax.swing.JInternalFrame {

    String usuario;

    /**
     * Creates new form IngresoMercaderiaPorLote
     */
    public IngresoMercaderiaPorLote() {
        initComponents();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        usuario = Login.user;
        labelTitulo.setText("Mercaderia>IngresoPorLote>CompraPorLote");

        LocalDate fecha = LocalDate.now();
        String fechas = fecha.format(DateTimeFormatter.ISO_DATE);
        labelfecha.setText(fechas);

        OperarcionesCRUD op = OperarcionesCRUD.getInstance();

        DefaultComboBoxModel modelo = (DefaultComboBoxModel) comboTipo.getModel();
        modelo.removeAllElements();

        DefaultComboBoxModel modeloProveed = (DefaultComboBoxModel) comboProveedor.getModel();
        modeloProveed.removeAllElements();

        //esto es para llenar los combos de tipo de producto y proveedor
        try {
            //combo tipoProducto
            Vector<String> listadoTipo = op.TipoProducto();
            for (String dato : listadoTipo) {
                modelo.addElement(dato);
            }
            if (!listadoTipo.isEmpty()) {
                modelo.setSelectedItem(listadoTipo.get(0));
            }

            //combo Proverdor
            ArrayList<Vector<String>> listaPRovee = op.NombresCompletosProveedor();

            for (Vector<String> vector : listaPRovee) {
                String nombre = vector.get(0);
                String apellidos = vector.get(1);
                modeloProveed.addElement(nombre + " " + apellidos);
            }

        } catch (SQLException err) {
            err.printStackTrace();

        }
        //esto es para activar el combo a credito
        DefaultTableModel modelodos = (DefaultTableModel) tablados.getModel();
        modelodos.setRowCount(0);
        labelPlazo.setVisible(false);
        comboplazo.setVisible(false);

        comboformapago.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {

                Object seleccionado = comboformapago.getSelectedItem();
                //if (e.getStateChange() == ItemEvent.SELECTED) verifica que el evento corresponde a un ítem que fue seleccionado, no deseleccionado.
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    if ("Crédito".equals(seleccionado)) {
                        labelPlazo.setVisible(true);
                        comboplazo.setVisible(true);

                    } else {
                        labelPlazo.setVisible(false);
                        comboplazo.setVisible(false);

                    }
                }
            }
        });

        //para eliminar un producto de la compra
        tablados.addMouseListener(new MouseAdapter() {
            @Override

            public void mouseClicked(MouseEvent e) {
                int fila_po = tablados.rowAtPoint(e.getPoint());

                if (fila_po > -1) {

                    int confirm = JOptionPane.showConfirmDialog(null, "¿Eliminar este Producto de la Compra?", "Confirmar", JOptionPane.YES_NO_OPTION);
                    if (confirm == JOptionPane.YES_OPTION) {
                        modelodos.removeRow(fila_po);
                    }
                }
            }

        });

        //para que solo permita ingresar valores numericos en cantidad
        txtcantidad.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    e.consume();
                }

            }

            @Override
            public void keyPressed(KeyEvent e) {

            }

            @Override
            public void keyReleased(KeyEvent e) {

            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUno = new javax.swing.JTable();
        AgregarCompra = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        comboProveedor = new javax.swing.JComboBox<>();
        BuscarTipo = new javax.swing.JButton();
        BuscarProveedor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdetalle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtiva = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        labelfecha = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        Limpiar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablados = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtSumaTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboformapago = new javax.swing.JComboBox<>();
        labelPlazo = new javax.swing.JLabel();
        comboplazo = new javax.swing.JComboBox<>();
        labelpagar = new javax.swing.JLabel();
        labelpagarCredito = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        CalcularPlazo = new javax.swing.JButton();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro-de-la-carretilla.png"))); // NOI18N

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salida.png"))); // NOI18N
        jButton1.setToolTipText("Salir");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(labelTitulo);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Busqueda por Tipo de Producto :");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTipo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                comboTipoComponentShown(evt);
            }
        });

        tablaUno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre ", "Detalle", "Precio", "Iva"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUno.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaUno);
        if (tablaUno.getColumnModel().getColumnCount() > 0) {
            tablaUno.getColumnModel().getColumn(0).setResizable(false);
            tablaUno.getColumnModel().getColumn(1).setResizable(false);
            tablaUno.getColumnModel().getColumn(2).setResizable(false);
            tablaUno.getColumnModel().getColumn(3).setResizable(false);
        }

        AgregarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mas.png"))); // NOI18N
        AgregarCompra.setText("Agregar");
        AgregarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCompraActionPerformed(evt);
            }
        });

        Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actualizar-flecha.png"))); // NOI18N
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        jLabel3.setText("Busqueda por Proveedor:");

        comboProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BuscarTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/consulta.png"))); // NOI18N
        BuscarTipo.setText("Buscar");
        BuscarTipo.setToolTipText("Buscar");
        BuscarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTipoActionPerformed(evt);
            }
        });

        BuscarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/consulta.png"))); // NOI18N
        BuscarProveedor.setText("Buscar");
        BuscarProveedor.setToolTipText("Buscar");
        BuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarProveedorActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre Producto:");

        txtnombres.setEditable(false);

        jLabel4.setText("Detalle Producto:");

        txtdetalle.setEditable(false);

        jLabel5.setText("Precio:");

        txtprecio.setEditable(false);

        jLabel6.setText("Iva:");

        txtiva.setEditable(false);

        jLabel9.setText("Fecha Registro:");

        jLabel10.setText("Cantidad");

        Limpiar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actualizar-flecha.png"))); // NOI18N
        Limpiar1.setText("Limpiar");
        Limpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpiar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboTipo, 0, 210, Short.MAX_VALUE)
                            .addComponent(comboProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BuscarTipo)
                            .addComponent(BuscarProveedor)))
                    .addComponent(labelfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdetalle, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(txtnombres))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel6)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtiva, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AgregarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Limpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuscarTipo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(comboProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BuscarProveedor))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Limpiar1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Limpiar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtdetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgregarCompra))
                        .addGap(0, 24, Short.MAX_VALUE))))
        );

        tablados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre del Producto", "Detalle del Producto", "Cantidad", "Precio", "Iva", "Total Compra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablados.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablados);
        if (tablados.getColumnModel().getColumnCount() > 0) {
            tablados.getColumnModel().getColumn(0).setResizable(false);
            tablados.getColumnModel().getColumn(1).setResizable(false);
            tablados.getColumnModel().getColumn(2).setResizable(false);
            tablados.getColumnModel().getColumn(3).setResizable(false);
            tablados.getColumnModel().getColumn(4).setResizable(false);
            tablados.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Suma Total:");

        txtSumaTotal.setEditable(false);

        jLabel8.setText("Forma de Pago:");

        comboformapago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contado", "Crédito" }));

        labelPlazo.setText("Plazo:");

        comboplazo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12 meses", "6 meses", "3 meses", "1 mes" }));

        labelpagar.setText("Valor a Pagar:");

        labelpagarCredito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disco-flexible.png"))); // NOI18N
        jButton4.setText("Guardar Compra");
        jButton4.setToolTipText("Guardar");

        CalcularPlazo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calcular.png"))); // NOI18N
        CalcularPlazo.setText("Calcular Plazo");
        CalcularPlazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularPlazoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(CalcularPlazo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSumaTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboformapago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelpagar)
                            .addComponent(labelPlazo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboplazo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelpagarCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSumaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboformapago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(CalcularPlazo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboplazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPlazo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelpagar)
                    .addComponent(labelpagarCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1522, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboTipoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_comboTipoComponentShown

    }//GEN-LAST:event_comboTipoComponentShown

    public void ActualizarTotales() {
        DefaultTableModel modelodos = (DefaultTableModel) tablados.getModel();
        String tota;
        double sumaTotal = 0.0;
        double val = 0.0;
        double diferido = 0.0;
        for (int i = 0; i < modelodos.getRowCount(); i++) {
            tota = (String) modelodos.getValueAt(i, 5);

            if (tota != null && !tota.trim().isEmpty()) {
                try {
                    val = Double.parseDouble(tota);
                    sumaTotal += val;
                } catch (NumberFormatException e) {
                    System.out.println("Error al convertir total" + tota);
                }
            } else {
                System.out.println("Valor nulo o vacío en columna 5, fila " + i);
            }
        }

        Object seleccionado = comboformapago.getSelectedItem();
        Object seleccion = comboplazo.getSelectedItem();

        if ("Crédito".equals(seleccionado)) {
            labelPlazo.setVisible(true);
            comboplazo.setVisible(true);

            if ("12 meses".equals(seleccion)) {
                diferido = sumaTotal / 12;
            } else if ("6 meses".equals(seleccion)) {
                diferido = sumaTotal / 6;
            } else if ("3 meses".equals(seleccion)) {
                diferido = sumaTotal / 3;
            } else if ("1 mes".equals(seleccion)) {
                diferido = sumaTotal / 1;
            }
            txtSumaTotal.setText(String.format("%.2f", sumaTotal));
            labelpagarCredito.setText(String.format("%.2f", diferido));
        } else {
            labelPlazo.setVisible(false);
            comboplazo.setVisible(false);
            txtSumaTotal.setText(String.format("%.2f", sumaTotal));
            labelpagarCredito.setText(String.format("%.2f", sumaTotal));

        }

    }
    private void BuscarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTipoActionPerformed
        String tipo;
        tipo = comboTipo.getSelectedItem().toString();
        try {
            OperarcionesCRUD op = OperarcionesCRUD.getInstance();
            ArrayList<Vector<String>> matriz = op.BusquedaProducto(tipo);

            DefaultTableModel modelo = (DefaultTableModel) tablaUno.getModel();
            modelo.setRowCount(0);

            for (Vector<String> vector : matriz) {
                String nombre, detalle, precio, iva;

                nombre = vector.get(1);
                detalle = vector.get(3);
                precio = vector.get(5);
                iva = vector.get(6);

                Vector<String> fila = new Vector<>();

                fila.add(nombre);
                fila.add(detalle);
                fila.add(precio);
                fila.add(iva);
                modelo.addRow(fila);
            }
            tablaUno.addMouseListener(new MouseAdapter() {
                @Override

                public void mouseClicked(MouseEvent e) {
                    int fila_point = tablaUno.rowAtPoint(e.getPoint());

                    if (fila_point > -1) {
                        String nombre = (String) modelo.getValueAt(fila_point, 0);
                        String detalle = (String) modelo.getValueAt(fila_point, 1);
                        String precio = (String) modelo.getValueAt(fila_point, 2);
                        String iva = (String) modelo.getValueAt(fila_point, 3);

                        txtnombres.setText(nombre);
                        txtdetalle.setText(detalle);
                        txtprecio.setText(precio);
                        txtiva.setText(iva);
                    }
                }
            });

        } catch (SQLException err) {
            err.printStackTrace();
        }
    }//GEN-LAST:event_BuscarTipoActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed

        Limpiar();
    }//GEN-LAST:event_LimpiarActionPerformed

    private void BuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarProveedorActionPerformed
        String valor, nombre, apellido;

        valor = (String) comboProveedor.getSelectedItem();

        if (valor != null && !valor.isEmpty()) {
            String[] partes = valor.trim().split(" ");

            nombre = partes[0];
            apellido = partes.length > 1 ? partes[1] : "";

            try {
                OperarcionesCRUD op = OperarcionesCRUD.getInstance();
                ArrayList<Vector<String>> matriz = op.BusquedaNombresProveedor(nombre, apellido);

                DefaultTableModel modelo = (DefaultTableModel) tablaUno.getModel();
                modelo.setRowCount(0);

                for (Vector<String> vector : matriz) {
                    String nombres, detalle, precio, iva;
                    nombres = vector.get(1);
                    detalle = vector.get(3);
                    precio = vector.get(5);
                    iva = vector.get(6);

                    Vector<String> vector2 = new Vector<>();

                    vector2.add(nombres);
                    vector2.add(detalle);
                    vector2.add(precio);
                    vector2.add(iva);

                    modelo.addRow(vector2);

                }

                tablaUno.addMouseListener(new MouseAdapter() {
                    @Override

                    public void mouseClicked(MouseEvent e) {
                        int fila_point = tablaUno.rowAtPoint(e.getPoint());

                        if (fila_point > -1) {
                            String nombres = (String) modelo.getValueAt(fila_point, 0);
                            String detalle = (String) modelo.getValueAt(fila_point, 1);
                            String precio = (String) modelo.getValueAt(fila_point, 2);
                            String iva = (String) modelo.getValueAt(fila_point, 3);

                            txtnombres.setText(nombres);
                            txtdetalle.setText(detalle);
                            txtprecio.setText(precio);
                            txtiva.setText(iva);
                        }
                    }
                });
            } catch (SQLException err) {
                err.printStackTrace();
            }
        }


    }//GEN-LAST:event_BuscarProveedorActionPerformed

    private void AgregarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCompraActionPerformed
        String nombre, detalle, precio, iva, cantidad, tota;
        int validar = 0;

        nombre = txtnombres.getText();
        detalle = txtdetalle.getText();
        precio = txtprecio.getText();
        iva = txtiva.getText();
        cantidad = txtcantidad.getText();
        DefaultTableModel modelo = (DefaultTableModel) tablados.getModel();

        try {
            if (cantidad.equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese una cantidad");
                validar++;
            }

            if (validar == 0) {

                int can = (Integer.parseInt(cantidad));
                double pre = (Double.parseDouble(precio));
                double iv = (Double.parseDouble(iva));

                double sub = can * pre;
                double impuesto = (sub * iv) / 100;
                double total = sub + impuesto;

                String totales = (String.valueOf(total));

                Vector<String> vector = new Vector<>();
                vector.add(nombre);
                vector.add(detalle);
                vector.add(cantidad);
                vector.add(precio);
                vector.add(iva);
                vector.add(totales);

                modelo.addRow(vector);

            } else {
                JOptionPane.showMessageDialog(null, "Seleccione un Producto");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al agregar producto" + e);
            System.out.println("Error al agregar producto" + e);
        }


    }//GEN-LAST:event_AgregarCompraActionPerformed

    public void actulaizarVisiblePalzo() {
        Object seleccionado = comboformapago.getSelectedItem();
        boolean esCredito = "Crédito".equals(seleccionado);

        labelPlazo.setVisible(true);
        comboplazo.setVisible(true);

    }
    private void Limpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpiar1ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tablaUno.getModel();
        modelo.setRowCount(0);
    }//GEN-LAST:event_Limpiar1ActionPerformed

    private void CalcularPlazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularPlazoActionPerformed
        ActualizarTotales();
    }//GEN-LAST:event_CalcularPlazoActionPerformed

    public void Limpiar() {
        txtnombres.setText("");
        txtdetalle.setText("");
        txtprecio.setText("");
        txtiva.setText("");
        txtcantidad.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCompra;
    private javax.swing.JButton BuscarProveedor;
    private javax.swing.JButton BuscarTipo;
    private javax.swing.JButton CalcularPlazo;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Limpiar1;
    private javax.swing.JComboBox<String> comboProveedor;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JComboBox<String> comboformapago;
    private javax.swing.JComboBox<String> comboplazo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelPlazo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelfecha;
    private javax.swing.JLabel labelpagar;
    private javax.swing.JLabel labelpagarCredito;
    private javax.swing.JTable tablaUno;
    private javax.swing.JTable tablados;
    private javax.swing.JTextField txtSumaTotal;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtdetalle;
    private javax.swing.JTextField txtiva;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
