/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logica_Operaciones_BD.OperarcionesCRUD;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author edand
 */
public class Principal extends javax.swing.JFrame {

    String usuario;
    TransaccionesIngreso transaccion;
    TransaccionesPolizas polizas;
    Cliente cliente;
    Registro registro;
    ActualizarUsuario ActUsuario;
    ActPassword actPassww;
    Productos Regisprod;
    RegistroProveedor RegProvee;
    EditarProductos editPro;
    IngresoMercaderia ingreMer;
    CompraPorLote compLote;
    AprobarCompra aprCom;
    ProcesarCompra procCom;
    ComprasDiarias compDia;
    IngresarAnulacionCompra ingreAnuCom;
    AprobacionAnulacionCompra1 aproAnulCom;
    ProcesarAnulacionCompra proAnulCom;
    IngresoMercaderiaPorLote ingreMercLote;
    ListaUsuarios listaUsuarios;
    ActPassUsuario actPassUser;
    ReportesClientes reClientes;
    ReportesProveedor reProveedor;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        usuario = Login.user;
        setTitle(" Sesion iniciada por " + usuario);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        OperarcionesCRUD op = OperarcionesCRUD.getInstance();
        try {
            String tiponivel = op.TipoNivelUser(usuario);
            if (tiponivel.equalsIgnoreCase("Administrador")) {
                Usuarios.setVisible(true);
            } else if (tiponivel.equalsIgnoreCase("Usuario")) {
                Usuarios.setVisible(false);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }

    @Override
    public Image getIconImage() {
        // Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/informationuser.png"));
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/ico.png"));
        return retValue;
    }

    private boolean cerrado(Object obj) {
        JInternalFrame[] FrmActivo = jDesktopPane2.getAllFrames();
        boolean cerrado = true;
        int i = 0;
        while (i < FrmActivo.length && cerrado) {
            if (FrmActivo[i] == obj) {
                cerrado = false;
            }
            i++;
        }
        return cerrado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        BarraMenu = new javax.swing.JMenuBar();
        Clientes = new javax.swing.JMenu();
        IngresoClientes = new javax.swing.JMenuItem();
        Mecaderia = new javax.swing.JMenu();
        RegistroProducto = new javax.swing.JMenuItem();
        ActualizarProducto = new javax.swing.JMenuItem();
        IngresoMercaderia = new javax.swing.JMenu();
        IngresoCompra = new javax.swing.JMenuItem();
        AprobarUnaCompra = new javax.swing.JMenuItem();
        ProcesarCompra = new javax.swing.JMenuItem();
        IngresoPorLote = new javax.swing.JMenu();
        IngresoCompraLote = new javax.swing.JMenuItem();
        AprobarCompraLote = new javax.swing.JMenuItem();
        ProcesarCompraLote = new javax.swing.JMenuItem();
        ComprasDiarias = new javax.swing.JMenuItem();
        Procesos = new javax.swing.JMenu();
        AnulacioCompra = new javax.swing.JMenu();
        IngresoAnulacion = new javax.swing.JMenuItem();
        AprobarAnulacion = new javax.swing.JMenuItem();
        ProcesarAnulacion = new javax.swing.JMenuItem();
        Ventas = new javax.swing.JMenu();
        RegistroProducto1 = new javax.swing.JMenuItem();
        ActualizarProducto1 = new javax.swing.JMenuItem();
        IngresoMercaderia1 = new javax.swing.JMenu();
        IngresoVenta = new javax.swing.JMenuItem();
        AprobarUnaVenta = new javax.swing.JMenuItem();
        ProcesarVenta = new javax.swing.JMenuItem();
        IngresoPorLote1 = new javax.swing.JMenu();
        IngresoCompraLote1 = new javax.swing.JMenuItem();
        AprobarCompraLote1 = new javax.swing.JMenuItem();
        ProcesarCompraLote1 = new javax.swing.JMenuItem();
        VentasDiarias = new javax.swing.JMenuItem();
        Procesos1 = new javax.swing.JMenu();
        AnulacionVenta = new javax.swing.JMenu();
        IngresoAnulacion1 = new javax.swing.JMenuItem();
        AprobarAnulacion1 = new javax.swing.JMenuItem();
        ProcesarAnulacion1 = new javax.swing.JMenuItem();
        Proveedor = new javax.swing.JMenu();
        Registro = new javax.swing.JMenuItem();
        Usuarios = new javax.swing.JMenu();
        RegistroUsuario = new javax.swing.JMenuItem();
        CambioPassword = new javax.swing.JMenuItem();
        ActualizacionUsuario = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        Reportes = new javax.swing.JMenu();
        JMenuClientes = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuMercadería = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuProveedor = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane2.setBackground(new java.awt.Color(204, 204, 204));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jDesktopPane2.setLayer(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );

        Clientes.setText("Clientes");
        Clientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        IngresoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clasificacion.png"))); // NOI18N
        IngresoClientes.setText("Ingreso Clientes");
        IngresoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoClientesActionPerformed(evt);
            }
        });
        Clientes.add(IngresoClientes);

        BarraMenu.add(Clientes);

        Mecaderia.setText("Mercaderia");
        Mecaderia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        RegistroProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar-producto.png"))); // NOI18N
        RegistroProducto.setText("Registro Productos");
        RegistroProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroProductoActionPerformed(evt);
            }
        });
        Mecaderia.add(RegistroProducto);

        ActualizarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lapiz.png"))); // NOI18N
        ActualizarProducto.setText("Editar Producto");
        ActualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarProductoActionPerformed(evt);
            }
        });
        Mecaderia.add(ActualizarProducto);

        IngresoMercaderia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar-producto1.png"))); // NOI18N
        IngresoMercaderia.setText("Ingreso Mercaderia");

        IngresoCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro.png"))); // NOI18N
        IngresoCompra.setText("Ingreso Compra");
        IngresoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoCompraActionPerformed(evt);
            }
        });
        IngresoMercaderia.add(IngresoCompra);

        AprobarUnaCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aprobado.png"))); // NOI18N
        AprobarUnaCompra.setText("Aprobar Compra");
        AprobarUnaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AprobarUnaCompraActionPerformed(evt);
            }
        });
        IngresoMercaderia.add(AprobarUnaCompra);

        ProcesarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jugar.png"))); // NOI18N
        ProcesarCompra.setText("Procesar Compra");
        ProcesarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcesarCompraActionPerformed(evt);
            }
        });
        IngresoMercaderia.add(ProcesarCompra);

        Mecaderia.add(IngresoMercaderia);

        IngresoPorLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro-de-la-carretilla.png"))); // NOI18N
        IngresoPorLote.setText("Ingreso por Lote");

        IngresoCompraLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro-de-la-carretilla.png"))); // NOI18N
        IngresoCompraLote.setText("Compra por Lote");
        IngresoCompraLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoCompraLoteActionPerformed(evt);
            }
        });
        IngresoPorLote.add(IngresoCompraLote);

        AprobarCompraLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aprobado.png"))); // NOI18N
        AprobarCompraLote.setText("Aprobar");
        IngresoPorLote.add(AprobarCompraLote);

        ProcesarCompraLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jugar.png"))); // NOI18N
        ProcesarCompraLote.setText("Procesar");
        IngresoPorLote.add(ProcesarCompraLote);

        Mecaderia.add(IngresoPorLote);

        ComprasDiarias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anadir.png"))); // NOI18N
        ComprasDiarias.setText("Compras Diarias");
        ComprasDiarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprasDiariasActionPerformed(evt);
            }
        });
        Mecaderia.add(ComprasDiarias);

        Procesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/engranajes.png"))); // NOI18N
        Procesos.setText("Procesos");

        AnulacioCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fracaso (1).png"))); // NOI18N
        AnulacioCompra.setText("Anulación Compra");

        IngresoAnulacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anadir.png"))); // NOI18N
        IngresoAnulacion.setText("Ingreso");
        IngresoAnulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoAnulacionActionPerformed(evt);
            }
        });
        AnulacioCompra.add(IngresoAnulacion);

        AprobarAnulacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aprobado.png"))); // NOI18N
        AprobarAnulacion.setText("Aprobar");
        AprobarAnulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AprobarAnulacionActionPerformed(evt);
            }
        });
        AnulacioCompra.add(AprobarAnulacion);

        ProcesarAnulacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jugar.png"))); // NOI18N
        ProcesarAnulacion.setText("Procesar");
        ProcesarAnulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcesarAnulacionActionPerformed(evt);
            }
        });
        AnulacioCompra.add(ProcesarAnulacion);

        Procesos.add(AnulacioCompra);

        Mecaderia.add(Procesos);

        BarraMenu.add(Mecaderia);

        Ventas.setText("Ventas");
        Ventas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        RegistroProducto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar-producto.png"))); // NOI18N
        RegistroProducto1.setText("Registro Productos");
        RegistroProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroProducto1ActionPerformed(evt);
            }
        });
        Ventas.add(RegistroProducto1);

        ActualizarProducto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lapiz.png"))); // NOI18N
        ActualizarProducto1.setText("Editar Producto");
        ActualizarProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarProducto1ActionPerformed(evt);
            }
        });
        Ventas.add(ActualizarProducto1);

        IngresoMercaderia1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar-producto1.png"))); // NOI18N
        IngresoMercaderia1.setText("Ingreso Mercaderia");

        IngresoVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro.png"))); // NOI18N
        IngresoVenta.setText("Ingreso Compra");
        IngresoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoVentaActionPerformed(evt);
            }
        });
        IngresoMercaderia1.add(IngresoVenta);

        AprobarUnaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aprobado.png"))); // NOI18N
        AprobarUnaVenta.setText("Aprobar Venta");
        AprobarUnaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AprobarUnaVentaActionPerformed(evt);
            }
        });
        IngresoMercaderia1.add(AprobarUnaVenta);

        ProcesarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jugar.png"))); // NOI18N
        ProcesarVenta.setText("Procesar Venta");
        ProcesarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcesarVentaActionPerformed(evt);
            }
        });
        IngresoMercaderia1.add(ProcesarVenta);

        Ventas.add(IngresoMercaderia1);

        IngresoPorLote1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro-de-la-carretilla.png"))); // NOI18N
        IngresoPorLote1.setText("Venta por Lote");

        IngresoCompraLote1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carro-de-la-carretilla.png"))); // NOI18N
        IngresoCompraLote1.setText("Venta por Lote");
        IngresoPorLote1.add(IngresoCompraLote1);

        AprobarCompraLote1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aprobado.png"))); // NOI18N
        AprobarCompraLote1.setText("Aprobar");
        IngresoPorLote1.add(AprobarCompraLote1);

        ProcesarCompraLote1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jugar.png"))); // NOI18N
        ProcesarCompraLote1.setText("Procesar");
        IngresoPorLote1.add(ProcesarCompraLote1);

        Ventas.add(IngresoPorLote1);

        VentasDiarias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anadir.png"))); // NOI18N
        VentasDiarias.setText("Ventas Diarias");
        Ventas.add(VentasDiarias);

        Procesos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/engranajes.png"))); // NOI18N
        Procesos1.setText("Procesos");

        AnulacionVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fracaso (1).png"))); // NOI18N
        AnulacionVenta.setText("Anulación Venta");

        IngresoAnulacion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/anadir.png"))); // NOI18N
        IngresoAnulacion1.setText("Ingreso");
        IngresoAnulacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoAnulacion1ActionPerformed(evt);
            }
        });
        AnulacionVenta.add(IngresoAnulacion1);

        AprobarAnulacion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aprobado.png"))); // NOI18N
        AprobarAnulacion1.setText("Aprobar");
        AnulacionVenta.add(AprobarAnulacion1);

        ProcesarAnulacion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jugar.png"))); // NOI18N
        ProcesarAnulacion1.setText("Procesar");
        AnulacionVenta.add(ProcesarAnulacion1);

        Procesos1.add(AnulacionVenta);

        Ventas.add(Procesos1);

        BarraMenu.add(Ventas);

        Proveedor.setText("Proveedor");
        Proveedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar.png"))); // NOI18N
        Registro.setText("Registro");
        Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroActionPerformed(evt);
            }
        });
        Proveedor.add(Registro);

        BarraMenu.add(Proveedor);

        Usuarios.setText("Usuarios");
        Usuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosActionPerformed(evt);
            }
        });

        RegistroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/perfil.png"))); // NOI18N
        RegistroUsuario.setText("Registro");
        RegistroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroUsuarioActionPerformed(evt);
            }
        });
        Usuarios.add(RegistroUsuario);

        CambioPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contrasena.png"))); // NOI18N
        CambioPassword.setText("Password");
        CambioPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambioPasswordActionPerformed(evt);
            }
        });
        Usuarios.add(CambioPassword);

        ActualizacionUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lapiz.png"))); // NOI18N
        ActualizacionUsuario.setText("Actualizar");
        ActualizacionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizacionUsuarioActionPerformed(evt);
            }
        });
        Usuarios.add(ActualizacionUsuario);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar.png"))); // NOI18N
        jMenuItem1.setText("Lista");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Usuarios.add(jMenuItem1);

        BarraMenu.add(Usuarios);

        Reportes.setText("Reportes");
        Reportes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        JMenuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clasificacion.png"))); // NOI18N
        JMenuClientes.setText("Clientes");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clasificacion.png"))); // NOI18N
        jMenuItem3.setText("Clientes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        JMenuClientes.add(jMenuItem3);

        Reportes.add(JMenuClientes);

        jMenuMercadería.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar-producto1.png"))); // NOI18N
        jMenuMercadería.setText("Mercadería");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar-producto.png"))); // NOI18N
        jMenuItem4.setText("Compra");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuMercadería.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconos-de-dinero.png"))); // NOI18N
        jMenuItem5.setText("Venta");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuMercadería.add(jMenuItem5);

        Reportes.add(jMenuMercadería);

        jMenuProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/equipo.png"))); // NOI18N
        jMenuProveedor.setText("Proveedor");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/transaccion.png"))); // NOI18N
        jMenuItem6.setText("Proveedor");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuProveedor.add(jMenuItem6);

        Reportes.add(jMenuProveedor);

        BarraMenu.add(Reportes);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoClientesActionPerformed
        try {
            if (cerrado(cliente)) {
                cliente = new Cliente();
                jTabbedPane1.add("Cliente", cliente);
                cliente.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Clientes ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana transacciones" + e);
        }
    }//GEN-LAST:event_IngresoClientesActionPerformed

    private void RegistroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroUsuarioActionPerformed

        try {
            if (cerrado(registro)) {
                registro = new Registro();
                jTabbedPane1.add("Registro Usuario", registro);
                registro.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Registro ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Resgistro Usuario" + e);
        }

    }//GEN-LAST:event_RegistroUsuarioActionPerformed

    private void UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosActionPerformed


    }//GEN-LAST:event_UsuariosActionPerformed

    private void ActualizacionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizacionUsuarioActionPerformed
        try {
            if (cerrado(ActUsuario)) {
                ActUsuario = new ActualizarUsuario();
                jTabbedPane1.add("Actualizar Usuario", ActUsuario);
                ActUsuario.show();

            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Actualizacion Usuario ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Actualizar Usuario" + e);
        }
    }//GEN-LAST:event_ActualizacionUsuarioActionPerformed

    private void CambioPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambioPasswordActionPerformed
        try {
            if (cerrado(actPassUser)) {
                actPassUser = new ActPassUsuario();
                jTabbedPane1.add("Actualizacion Password", actPassUser);
                actPassUser.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Actualizacion Password ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Actualizar Password" + e);
        }
    }//GEN-LAST:event_CambioPasswordActionPerformed

    private void RegistroProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroProductoActionPerformed
        try {
            if (cerrado(Regisprod)) {
                Regisprod = new Productos();
                jTabbedPane1.add("Registro Productos", Regisprod);
                Regisprod.show();

            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Registro Producto ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Registro Producto" + e);
        }
    }//GEN-LAST:event_RegistroProductoActionPerformed

    private void RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroActionPerformed
        try {
            if (cerrado(RegProvee)) {
                RegProvee = new RegistroProveedor();
                jTabbedPane1.add("Registro Proveedor", RegProvee);
                RegProvee.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Registro Proveedor ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Registro Proveedor" + e);
        }
    }//GEN-LAST:event_RegistroActionPerformed

    private void ActualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarProductoActionPerformed
        try {
            if (cerrado(editPro)) {
                editPro = new EditarProductos();
                jTabbedPane1.add("Editar Productos", editPro);
                editPro.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Editar Productos ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Editar Productos" + e);
        }
    }//GEN-LAST:event_ActualizarProductoActionPerformed

    private void IngresoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoCompraActionPerformed
        try {
            if (cerrado(ingreMer)) {
                ingreMer = new IngresoMercaderia();
                jTabbedPane1.add("Compra Mercaderia", ingreMer);
                ingreMer.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Una Compra ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Una Compra" + e);
        }

    }//GEN-LAST:event_IngresoCompraActionPerformed

    private void AprobarUnaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AprobarUnaCompraActionPerformed
        try {
            if (cerrado(aprCom)) {
                aprCom = new AprobarCompra();
                jTabbedPane1.add("Aprobar Compra", aprCom);
                aprCom.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Aprobar Compra ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Aprobar Compra" + e);
        }
    }//GEN-LAST:event_AprobarUnaCompraActionPerformed

    private void ProcesarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcesarCompraActionPerformed
        try {
            if (cerrado(procCom)) {
                procCom = new ProcesarCompra();
                jTabbedPane1.add("Procesar Compra ", procCom);
                procCom.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Procesar Compra ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Procesar Compra" + e);
        }
    }//GEN-LAST:event_ProcesarCompraActionPerformed

    private void IngresoAnulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoAnulacionActionPerformed
        try {
            if (cerrado(ingreAnuCom)) {
                ingreAnuCom = new IngresarAnulacionCompra();
                jTabbedPane1.add("Ingreso Anulación Compra", ingreAnuCom);
                ingreAnuCom.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Ingreso Anulación Compra ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Ingreso Anulación Compra" + e);
        }
    }//GEN-LAST:event_IngresoAnulacionActionPerformed

    private void RegistroProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroProducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroProducto1ActionPerformed

    private void ActualizarProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarProducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActualizarProducto1ActionPerformed

    private void IngresoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresoVentaActionPerformed

    private void AprobarUnaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AprobarUnaVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AprobarUnaVentaActionPerformed

    private void ProcesarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcesarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProcesarVentaActionPerformed

    private void IngresoAnulacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoAnulacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresoAnulacion1ActionPerformed

    private void ComprasDiariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprasDiariasActionPerformed
        try {
            if (cerrado(compDia)) {
                compDia = new ComprasDiarias();
                jTabbedPane1.add("Compras Diarias", compDia);
                compDia.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Compras Diarias ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana ompras Diarias" + e);
        }
    }//GEN-LAST:event_ComprasDiariasActionPerformed

    private void AprobarAnulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AprobarAnulacionActionPerformed
        try {
            if (cerrado(aproAnulCom)) {
                aproAnulCom = new AprobacionAnulacionCompra1();
                jTabbedPane1.add("Aprobacion Anulacion Compra", aproAnulCom);
                aproAnulCom.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Aprobacion Anulacion Compra ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Aprobacion Anulacion Compras" + e);
        }
    }//GEN-LAST:event_AprobarAnulacionActionPerformed

    private void ProcesarAnulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcesarAnulacionActionPerformed
        try {
            if (cerrado(proAnulCom)) {
                proAnulCom = new ProcesarAnulacionCompra();
                jTabbedPane1.add("Procesar Anulacion Compra", proAnulCom);
                proAnulCom.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Procesar Anulacion Compra ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Procesar Anulacion Compras" + e);
        }
    }//GEN-LAST:event_ProcesarAnulacionActionPerformed

    private void IngresoCompraLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoCompraLoteActionPerformed
        try {
            if (cerrado(ingreMercLote)) {
                ingreMercLote = new IngresoMercaderiaPorLote();
                jTabbedPane1.add("Ingreso Mercaderia Por Lote", ingreMercLote);
                ingreMercLote.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Ingreso Mercaderia Por Lote ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Ingreso Mercaderia por Lote" + e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_IngresoCompraLoteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            if (cerrado(listaUsuarios)) {
                listaUsuarios = new ListaUsuarios();
                jTabbedPane1.add("Lista Usuarios", listaUsuarios);
                listaUsuarios.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Lista Usuarios ya se Encuentra abierta");
            }

        } catch (Exception e) {
            System.err.println("Error al cargar ventana Lista Usuarios" + e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            if (cerrado(reClientes)) {
                reClientes = new ReportesClientes();
                jTabbedPane1.add("Reporte Clientes", reClientes);
                reClientes.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Reportes Clientes ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Reportes Clientes" + e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        try {
            if (cerrado(reProveedor)) {
                reProveedor = new ReportesProveedor();
                jTabbedPane1.add("Reportes Proveedor", reProveedor);
                reProveedor.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Reportes Proveedor ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Reportes Proveedor" + e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ActualizacionUsuario;
    private javax.swing.JMenuItem ActualizarProducto;
    private javax.swing.JMenuItem ActualizarProducto1;
    private javax.swing.JMenu AnulacioCompra;
    private javax.swing.JMenu AnulacionVenta;
    private javax.swing.JMenuItem AprobarAnulacion;
    private javax.swing.JMenuItem AprobarAnulacion1;
    private javax.swing.JMenuItem AprobarCompraLote;
    private javax.swing.JMenuItem AprobarCompraLote1;
    private javax.swing.JMenuItem AprobarUnaCompra;
    private javax.swing.JMenuItem AprobarUnaVenta;
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenuItem CambioPassword;
    private javax.swing.JMenu Clientes;
    private javax.swing.JMenuItem ComprasDiarias;
    private javax.swing.JMenuItem IngresoAnulacion;
    private javax.swing.JMenuItem IngresoAnulacion1;
    private javax.swing.JMenuItem IngresoClientes;
    private javax.swing.JMenuItem IngresoCompra;
    private javax.swing.JMenuItem IngresoCompraLote;
    private javax.swing.JMenuItem IngresoCompraLote1;
    private javax.swing.JMenu IngresoMercaderia;
    private javax.swing.JMenu IngresoMercaderia1;
    private javax.swing.JMenu IngresoPorLote;
    private javax.swing.JMenu IngresoPorLote1;
    private javax.swing.JMenuItem IngresoVenta;
    private javax.swing.JMenu JMenuClientes;
    private javax.swing.JMenu Mecaderia;
    private javax.swing.JMenuItem ProcesarAnulacion;
    private javax.swing.JMenuItem ProcesarAnulacion1;
    private javax.swing.JMenuItem ProcesarCompra;
    private javax.swing.JMenuItem ProcesarCompraLote;
    private javax.swing.JMenuItem ProcesarCompraLote1;
    private javax.swing.JMenuItem ProcesarVenta;
    private javax.swing.JMenu Procesos;
    private javax.swing.JMenu Procesos1;
    private javax.swing.JMenu Proveedor;
    private javax.swing.JMenuItem Registro;
    private javax.swing.JMenuItem RegistroProducto;
    private javax.swing.JMenuItem RegistroProducto1;
    private javax.swing.JMenuItem RegistroUsuario;
    private javax.swing.JMenu Reportes;
    private javax.swing.JMenu Usuarios;
    private javax.swing.JMenu Ventas;
    private javax.swing.JMenuItem VentasDiarias;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu jMenuMercadería;
    private javax.swing.JMenu jMenuProveedor;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
