/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

/**
 *
 * @author edand
 */
public class Principal extends javax.swing.JFrame {

    String usuario;
    TransaccionesIngreso transaccion;
    TransaccionesPolizas polizas;
    Cliente cliente;
    Registro registro;
    ActualizarUsuario ActUsuario;
    ActPassword actPassww;
    Productos Regisprod;
    RegistroProveedor RegProvee;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        usuario = Login.user;
        setTitle(" Sesion iniciada por " + usuario);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }

    @Override
    public Image getIconImage() {
        // Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/informationuser.png"));
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/ico.png"));
        return retValue;
    }

    private boolean cerrado(Object obj) {
        JInternalFrame[] FrmActivo = jDesktopPane2.getAllFrames();
        boolean cerrado = true;
        int i = 0;
        while (i < FrmActivo.length && cerrado) {
            if (FrmActivo[i] == obj) {
                cerrado = false;
            }
            i++;
        }
        return cerrado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Clientes = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        Productos = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        Ventas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Proveedor = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ActualizarUsuario = new javax.swing.JMenu();
        RegistroUsuario = new javax.swing.JMenuItem();
        CambioPassword = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        Opciones = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));

        jDesktopPane2.setLayer(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );

        Clientes.setText("Clientes");
        Clientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clasificacion.png"))); // NOI18N
        jMenuItem3.setText("Ingreso Clientes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Clientes.add(jMenuItem3);

        jMenuBar1.add(Clientes);

        Productos.setText("Productos");
        Productos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar-producto.png"))); // NOI18N
        jMenuItem6.setText("Registro Productos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        Productos.add(jMenuItem6);

        jMenuBar1.add(Productos);

        Ventas.setText("Ventas");
        Ventas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VentasMouseClicked(evt);
            }
        });
        Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Ingreso");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Ventas.add(jMenuItem1);

        jMenuItem2.setText("Polizas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Ventas.add(jMenuItem2);

        jMenuBar1.add(Ventas);

        Proveedor.setText("Proveedor");
        Proveedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar.png"))); // NOI18N
        jMenuItem5.setText("Registro");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        Proveedor.add(jMenuItem5);

        jMenuBar1.add(Proveedor);

        jMenu5.setText("Reportes");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu5);

        ActualizarUsuario.setText("Usuarios");
        ActualizarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ActualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarUsuarioActionPerformed(evt);
            }
        });

        RegistroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/perfil.png"))); // NOI18N
        RegistroUsuario.setText("Registro");
        RegistroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroUsuarioActionPerformed(evt);
            }
        });
        ActualizarUsuario.add(RegistroUsuario);

        CambioPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contrasena.png"))); // NOI18N
        CambioPassword.setText("Password");
        CambioPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambioPasswordActionPerformed(evt);
            }
        });
        ActualizarUsuario.add(CambioPassword);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lapiz.png"))); // NOI18N
        jMenuItem4.setText("Actualizar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        ActualizarUsuario.add(jMenuItem4);

        jMenuBar1.add(ActualizarUsuario);

        Opciones.setText("Opciones");
        Opciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(Opciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasActionPerformed


    }//GEN-LAST:event_VentasActionPerformed

    private void VentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentasMouseClicked

    }//GEN-LAST:event_VentasMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            if (cerrado(transaccion)) {
                transaccion = new TransaccionesIngreso();
                jTabbedPane1.add("Ingreso", transaccion);
                transaccion.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Transacciones ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana transacciones" + e);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            if (cerrado(polizas)) {
                polizas = new TransaccionesPolizas();
                jTabbedPane1.add("Polizas", polizas);
                polizas.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Polizas ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana transacciones" + e);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            if (cerrado(cliente)) {
                cliente = new Cliente();
                jTabbedPane1.add("Cliente", cliente);
                cliente.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Clientes ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana transacciones" + e);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void RegistroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroUsuarioActionPerformed

        try {
            if (cerrado(registro)) {
                registro = new Registro();
                jTabbedPane1.add("Registro Usuario", registro);
                registro.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Registro ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Resgistro Usuario" + e);
        }

    }//GEN-LAST:event_RegistroUsuarioActionPerformed

    private void ActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarUsuarioActionPerformed


    }//GEN-LAST:event_ActualizarUsuarioActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            if (cerrado(ActUsuario)) {
                ActUsuario = new ActualizarUsuario();
                jTabbedPane1.add("Actualizar Usuario", ActUsuario);
                ActUsuario.show();

            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Actualizacion Usuario ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Actualizar Usuario" + e);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void CambioPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambioPasswordActionPerformed
        try {
            if (cerrado(actPassww)) {
                actPassww = new ActPassword();
                jTabbedPane1.add("Actualizacion Password", actPassww);
                actPassww.show();
            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Actualizacion Password ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Actualizar Password" + e);
        }
    }//GEN-LAST:event_CambioPasswordActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        try {
            if (cerrado(Regisprod)) {
                Regisprod = new Productos();
                jTabbedPane1.add("Registro Productos", Regisprod);
                Regisprod.show();

            } else {
                JOptionPane.showMessageDialog(this, "La Ventana Registro Producto ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Registro Producto" + e);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            if (cerrado(RegProvee)) {
                RegProvee = new RegistroProveedor();
                jTabbedPane1.add("Registro Proveedor", RegProvee);
                RegProvee.show();
            }else{
                JOptionPane.showMessageDialog(this, "La Ventana Registro Proveedor ya se Encuentra abierta");
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ventana Registro Proveedor" + e);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ActualizarUsuario;
    private javax.swing.JMenuItem CambioPassword;
    private javax.swing.JMenu Clientes;
    private javax.swing.JMenu Opciones;
    private javax.swing.JMenu Productos;
    private javax.swing.JMenu Proveedor;
    private javax.swing.JMenuItem RegistroUsuario;
    private javax.swing.JMenu Ventas;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
